# Scalingo docker compose for local dev environment

version: "3.7"
services:
  php:
    build:
      context: api/
    volumes:
      - ./api:/srv/api:rw,cached
      - ./api/docker/php/conf.d/api-platform.dev.ini/:/usr/local/etc/php/conf.d/api-platform.ini
    environment:
      APP_ENV: "dev"
      APP_SECRET: "pC{]pvf)Me#Snx/AH7Q-,L|K`IM0c9C%]JTxSQCmzSo2/ckQ38EzL/73JRN4Sl?S"
      CORS_ALLOW_ORIGIN: "*"
      DATABASE_URL: "postgresql://my-user:my-user-password@postgres/api-platform"
    depends_on:
      - postgres

  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: "my-user"
      POSTGRES_PASSWORD: "my-user-password"
      POSTGRES_DB: "api-platform"
    volumes:
      - ./docker/postgresql:/var/lib/postgresql/data

  nginx:
    image: nginx:1
    ports:
      - 3000:80
    volumes:
      - ./api/docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./api/public:/app:ro
    depends_on:
      - php

  composer:
    image: composer:1
    working_dir: /app
    restart: 'no'
    volumes:
      - ./api:/app
